[package]
name = "physics-engine"
version = "0.1.0"
rust-version = "1.88"
edition = "2024"

[dependencies]
wgpu = "26.0.0"
env_logger = "0.11"
winit = { version = "0.30.8", features = ["android-native-activity"] }
pollster = "0.4"
bytemuck = { version = "1.16", features = ["derive"] }
